// Custom beats management system
export interface CustomBeat {
  beatNumber?: number; // Optional since we'll calculate it
  date: string; // YYYY-MM-DD format
  grid: boolean[][];
  bpm: number;
  title?: string;
  description?: string;
  creator?: string;
  category?: "weekly" | "holiday" | "guest" | "special";
}

// Predefined weekly beats for testing engagement
const weeklyBeats: CustomBeat[] = [
  // Add your 7 beats here - I'll create placeholders for now
  // You can replace these with your actual beats
  {
    date: "2025-07-31", // Today - Thursday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Thursday Beat",
    description: "Today's custom beat",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-01", // Friday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Friday Freedom",
    description: "Weekend vibes are here!",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-02", // Saturday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Saturday Sessions",
    description: "Weekend party starter",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-03", // Sunday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    ],
    bpm: 96,
    title: "Sunday Chill",
    description: "Relax and reflect on your week",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-04", // Monday
    grid: [
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 100,
    title: "Monday Motivation",
    description: "Start your week with this energizing groove",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-05", // Tuesday
    grid: [
      [
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 89,
    title: "Tuesday Tension",
    description: "A bit more complex to keep you engaged",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-06", // Wednesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 93,
    title: "Hump Day Hype",
    description: "Midweek energy boost",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-07", // Thursday
    grid: [
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 99,
    title: "Thursday Thrills",
    description: "Almost there! Keep the momentum going",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-08", // Friday
    grid: [
      [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 100,
    title: "Friday Freedom II",
    description: "Another weekend celebration!",
    creator: "beatkerri_team",
    category: "weekly",
  },
  // Extended week: August 9-15, 2025
  {
    date: "2025-08-09", // Saturday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 114,
    title: "Saturday Floor",
    description: "Four-on-the-floor house vibes",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-10", // Sunday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Sunday Trap",
    description: "Trap beats for the weekend",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-11", // Monday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 107,
    title: "Monday Reggae",
    description: "Start the week with reggae vibes",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-12", // Tuesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Tuesday Boom",
    description: "Classic boom bap energy",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-13", // Wednesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Wednesday 808s",
    description: "Mid-week 808 madness",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-14", // Thursday
    grid: [
      [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 99,
    title: "Thursday UKG",
    description: "UK Garage rhythms",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-15", // Friday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 111,
    title: "Friday Funk",
    description: "Funky Friday finale!",
    creator: "junkerri",
    category: "weekly",
  },
];

// In-memory storage for custom beats (in production, this would be a database)
let customBeats: CustomBeat[] = [];

// Initialize custom beats system
const initializeCustomBeats = () => {
  if (typeof window === "undefined") return; // Skip on server-side

  try {
    const stored = localStorage.getItem("beatkerri_custom_beats");
    if (stored) {
      const storedBeats = JSON.parse(stored);
      // Check if stored beats have the old 3-row structure
      const hasOldStructure = storedBeats.some(
        (beat: any) =>
          beat.grid && Array.isArray(beat.grid) && beat.grid.length === 3
      );

      if (hasOldStructure) {
        console.log(
          "Found old 3-row custom beats in localStorage, clearing and reinitializing..."
        );
        localStorage.removeItem("beatkerri_custom_beats");
        customBeats = [];
      } else {
        customBeats = storedBeats;
      }
    }

    // Add weekly beats if they don't already exist
    weeklyBeats.forEach((weeklyBeat) => {
      if (!customBeats.some((beat) => beat.date === weeklyBeat.date)) {
        customBeats.push(weeklyBeat);
      }
    });

    // Save to localStorage to ensure custom beats are persisted
    if (typeof window !== "undefined") {
      try {
        localStorage.setItem(
          "beatkerri_custom_beats",
          JSON.stringify(customBeats)
        );
      } catch (error) {
        console.error("Failed to save custom beats:", error);
      }
    }

    console.log("Custom beats initialized:", {
      totalBeats: customBeats.length,
      dates: customBeats.map((b) => b.date),
    });
  } catch (error) {
    console.error("Failed to load custom beats:", error);
    // Initialize with weekly beats even if localStorage fails
    weeklyBeats.forEach((weeklyBeat) => {
      if (!customBeats.some((beat) => beat.date === weeklyBeat.date)) {
        customBeats.push(weeklyBeat);
      }
    });
  }
};

// Initialize on client-side only
if (typeof window !== "undefined") {
  // Initialize immediately to avoid race conditions
  initializeCustomBeats();

  // Force a small delay to ensure custom beats are loaded before any components try to use them
  setTimeout(() => {
    console.log("Custom beats loaded:", {
      totalBeats: customBeats.length,
      dates: customBeats.map((b) => b.date),
      todayBeat: customBeats.find(
        (b) => b.date === new Date().toISOString().split("T")[0]
      ),
    });
  }, 100);
}

// Get custom beat for a specific date
export const getCustomBeat = (date: string): CustomBeat | null => {
  return customBeats.find((beat) => beat.date === date) || null;
};

// Add a custom beat
export const addCustomBeat = (beat: CustomBeat): void => {
  // Remove existing beat for the same date if it exists
  customBeats = customBeats.filter((b) => b.date !== beat.date);

  // Add the new beat
  customBeats.push(beat);

  // Save to localStorage
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(
        "beatkerri_custom_beats",
        JSON.stringify(customBeats)
      );
    } catch (error) {
      console.error("Failed to save custom beats:", error);
    }
  }
};

// Remove a custom beat
export const removeCustomBeat = (date: string): void => {
  customBeats = customBeats.filter((b) => b.date !== date);
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(
        "beatkerri_custom_beats",
        JSON.stringify(customBeats)
      );
    } catch (error) {
      console.error("Failed to save custom beats:", error);
    }
  }
};

// Get all custom beats
export const getAllCustomBeats = (): CustomBeat[] => {
  return [...customBeats];
};

// Check if a date has a custom beat
export const hasCustomBeat = (date: string): boolean => {
  return customBeats.some((beat) => beat.date === date);
};

// Clear localStorage and reinitialize custom beats (for testing)
export const clearAndReinitializeCustomBeats = (): void => {
  if (typeof window !== "undefined") {
    localStorage.removeItem("beatkerri_custom_beats");
    customBeats = [];
    initializeCustomBeats();
    console.log("Custom beats cleared and reinitialized");
  }
};

// Get beat for a specific date (custom or generated)
export const getBeatForDate = (
  date: string,
  generatedBeat: boolean[][],
  generatedBpm: number
): {
  grid: boolean[][];
  bpm: number;
  isCustom: boolean;
  title?: string;
  description?: string;
  creator?: string;
  category?: string;
} => {
  const customBeat = getCustomBeat(date);

  if (customBeat) {
    return {
      grid: customBeat.grid,
      bpm: customBeat.bpm,
      isCustom: true,
      title: customBeat.title,
      description: customBeat.description,
      creator: customBeat.creator,
      category: customBeat.category,
    };
  }

  return {
    grid: generatedBeat,
    bpm: generatedBpm,
    isCustom: false,
  };
};
