// Custom beats management system
export interface CustomBeat {
  beatNumber?: number; // Optional since we'll calculate it
  date: string; // YYYY-MM-DD format
  grid: boolean[][];
  bpm: number;
  title?: string;
  description?: string;
  creator?: string;
  category?: "weekly" | "holiday" | "guest" | "special";
}

// Predefined weekly beats for testing engagement
const weeklyBeats: CustomBeat[] = [
  // Add your 7 beats here - I'll create placeholders for now
  // You can replace these with your actual beats
  {
    date: "2025-07-31", // Today - Thursday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Thursday Beat",
    description: "Today's custom beat",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-01", // Friday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Friday Freedom",
    description: "Weekend vibes are here!",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-02", // Saturday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Saturday Sessions",
    description: "Weekend party starter",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-03", // Sunday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    ],
    bpm: 96,
    title: "Sunday Chill",
    description: "Relax and reflect on your week",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-04", // Monday
    grid: [
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 100,
    title: "Monday Motivation",
    description: "Start your week with this energizing groove",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-05", // Tuesday
    grid: [
      [
        true,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 89,
    title: "Tuesday Tension",
    description: "A bit more complex to keep you engaged",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-06", // Wednesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 93,
    title: "Hump Day Hype",
    description: "Midweek energy boost",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-07", // Thursday
    grid: [
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 99,
    title: "Thursday Thrills",
    description: "Almost there! Keep the momentum going",
    creator: "beatkerri_team",
    category: "weekly",
  },
  {
    date: "2025-08-08", // Friday
    grid: [
      [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 100,
    title: "Friday Freedom II",
    description: "Another weekend celebration!",
    creator: "beatkerri_team",
    category: "weekly",
  },
  // Extended week: August 9-15, 2025
  {
    date: "2025-08-09", // Saturday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 114,
    title: "Saturday Floor",
    description: "Four-on-the-floor house vibes",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-10", // Sunday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Sunday Trap",
    description: "Trap beats for the weekend",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-11", // Monday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 107,
    title: "Monday Reggae",
    description: "Start the week with reggae vibes",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-12", // Tuesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Tuesday Boom",
    description: "Classic boom bap energy",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-13", // Wednesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Wednesday 808s",
    description: "Mid-week 808 madness",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-14", // Thursday
    grid: [
      [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 99,
    title: "Thursday UKG",
    description: "UK Garage rhythms",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-15", // Friday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 111,
    title: "Friday Funk",
    description: "Funky Friday finale!",
    creator: "junkerri",
    category: "weekly",
  },
  // August 16-22, 2025 beats - Real beats from junkerri
  {
    date: "2025-08-16", // Saturday
    grid: [
      [
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 90,
    title: "Saturday Jazz",
    description: "jazz",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-17", // Sunday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 108,
    title: "Sunday Funky",
    description: "funky",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-18", // Monday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Monday Motn",
    description: "motn",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-19", // Tuesday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
    ],
    bpm: 109,
    title: "Tuesday Dub",
    description: "dub",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-20", // Wednesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Wednesday Pop",
    description: "pop",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-21", // Thursday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 98,
    title: "Thursday R&B",
    description: "rnb",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-22", // Friday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Friday Tek",
    description: "tek",
    creator: "junkerri",
    category: "weekly",
  },
  // August 30 - September 5, 2025 beats - Custom beats from junkerri
  {
    date: "2025-08-30", // Saturday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 114,
    title: "Saturday Rock",
    description: "rock",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-08-31", // Sunday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 120,
    title: "Sunday Afro",
    description: "afro",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-09-01", // Monday
    grid: [
      [
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 105,
    title: "Monday DnB",
    description: "dnb",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-09-02", // Tuesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 117,
    title: "Tuesday Jazz",
    description: "jazz",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-09-03", // Wednesday
    grid: [
      [
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 111,
    title: "Wednesday Latin",
    description: "latin",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-09-04", // Thursday
    grid: [
      [
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
    ],
    bpm: 110,
    title: "Thursday Electro",
    description: "electro",
    creator: "junkerri",
    category: "weekly",
  },
  {
    date: "2025-09-05", // Friday
    grid: [
      [
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
      ],
      [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
      ],
    ],
    bpm: 105,
    title: "Friday Bounce",
    description: "bounce",
    creator: "junkerri",
    category: "weekly",
  },
];

// In-memory storage for custom beats (in production, this would be a database)
let customBeats: CustomBeat[] = [];
let isInitialized = false;
const initCallbacks: Array<() => void> = [];

// Register a callback to be called when custom beats are loaded
export const onCustomBeatsLoaded = (callback: () => void) => {
  if (isInitialized) {
    callback();
  } else {
    initCallbacks.push(callback);
  }
};

/**
 * Validates and normalizes a grid to ensure it's 7x16 with all boolean values
 * This prevents glitches where user input doesn't register due to:
 * - Sparse arrays (missing values)
 * - Wrong dimensions
 * - Non-boolean values (undefined, null, etc.)
 */
const validateAndNormalizeGrid = (
  grid: any,
  filename: string
): boolean[][] | null => {
  // Check if grid is an array
  if (!Array.isArray(grid)) {
    console.error(
      `❌ Grid validation failed for ${filename}: grid is not an array`
    );
    return null;
  }

  // Check if grid has exactly 7 rows
  if (grid.length !== 7) {
    console.error(
      `❌ Grid validation failed for ${filename}: expected 7 rows, got ${grid.length}`
    );
    return null;
  }

  // Validate and normalize each row
  const normalizedGrid: boolean[][] = [];
  for (let rowIndex = 0; rowIndex < 7; rowIndex++) {
    const row = grid[rowIndex];

    // Check if row is an array
    if (!Array.isArray(row)) {
      console.error(
        `❌ Grid validation failed for ${filename}: row ${rowIndex} is not an array`
      );
      return null;
    }

    // Check if row has exactly 16 columns
    if (row.length !== 16) {
      console.warn(
        `⚠️ Grid validation warning for ${filename}: row ${rowIndex} has ${row.length} columns, expected 16. Normalizing...`
      );
    }

    // Normalize row to exactly 16 booleans
    const normalizedRow: boolean[] = [];
    for (let colIndex = 0; colIndex < 16; colIndex++) {
      const value = row[colIndex];
      // Convert to strict boolean, treat undefined/null/missing as false
      normalizedRow.push(Boolean(value));
    }
    normalizedGrid.push(normalizedRow);
  }

  console.log(`✅ Grid validation passed for ${filename}`);
  return normalizedGrid;
};

// Load custom beats from JSON files in public folder
const loadCustomBeatsFromFiles = async (): Promise<CustomBeat[]> => {
  if (typeof window === "undefined") return []; // Skip on server-side

  const beats: CustomBeat[] = [];
  // Map each date to its specific filename
  const dateToFilename: Record<string, string> = {
    "2025-11-7": "2025-11-7-1755898790798.json",
    "2025-11-8": "2025-11-8-1755898822617.json",
    "2025-11-9": "2025-11-9-1755898868125.json",
    "2025-11-10": "2025-11-10-1755898950167.json",
    "2025-11-11": "2025-11-11-1755898980455.json",
    "2025-11-12": "2025-11-12-1755899019440.json",
    "2025-11-13": "2025-11-13-1755899061410.json",
  };

  for (const [fileDate, filename] of Object.entries(dateToFilename)) {
    try {
      // Extract date parts and format as YYYY-MM-DD (with zero-padded day)
      const [year, month, day] = fileDate.split("-");
      const formattedDate = `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;

      const response = await fetch(`/custom-beats/Nov 7 - Nov 13/${filename}`);

      if (response.ok) {
        const beatData = await response.json();

        if (beatData && beatData.grid && beatData.bpm) {
          // Validate and normalize the grid
          const validatedGrid = validateAndNormalizeGrid(
            beatData.grid,
            filename
          );

          if (validatedGrid) {
            beats.push({
              date: formattedDate,
              grid: validatedGrid,
              bpm: beatData.bpm,
              title: beatData.name || `Custom Beat ${formattedDate}`,
              description: beatData.description || "",
              creator: beatData.author || "junkerri",
              category: "weekly" as const,
            });
            console.log(
              `✓ Successfully loaded custom beat for ${formattedDate} from ${filename}`
            );
          } else {
            console.error(
              `✗ Skipping ${filename} due to grid validation failure`
            );
          }
        } else {
          console.warn(
            `⚠️ Skipping ${filename}: missing required fields (grid or bpm)`
          );
        }
      }
    } catch (error) {
      console.error(`Failed to load beat for ${fileDate}:`, error);
    }
  }

  return beats;
};

// Initialize custom beats system
const initializeCustomBeats = async () => {
  if (typeof window === "undefined") return; // Skip on server-side

  try {
    const stored = localStorage.getItem("beatkerri_custom_beats");
    if (stored) {
      const storedBeats = JSON.parse(stored);
      // Check if stored beats have the old 3-row structure
      const hasOldStructure = storedBeats.some(
        (beat: any) =>
          beat.grid && Array.isArray(beat.grid) && beat.grid.length === 3
      );

      if (hasOldStructure) {
        console.log(
          "Found old 3-row custom beats in localStorage, clearing and reinitializing..."
        );
        localStorage.removeItem("beatkerri_custom_beats");
        customBeats = [];
      } else {
        customBeats = storedBeats;
      }
    }

    // Load custom beats from JSON files (Nov 7-13, 2025)
    const fileBeats = await loadCustomBeatsFromFiles();
    fileBeats.forEach((beat) => {
      // Remove existing beat for the same date if it exists
      customBeats = customBeats.filter((b) => b.date !== beat.date);
      customBeats.push(beat);
    });

    // Add weekly beats if they don't already exist
    weeklyBeats.forEach((weeklyBeat) => {
      if (!customBeats.some((beat) => beat.date === weeklyBeat.date)) {
        customBeats.push(weeklyBeat);
      }
    });

    // Save to localStorage to ensure custom beats are persisted
    if (typeof window !== "undefined") {
      try {
        localStorage.setItem(
          "beatkerri_custom_beats",
          JSON.stringify(customBeats)
        );
      } catch (error) {
        console.error("Failed to save custom beats:", error);
      }
    }

    console.log("Custom beats initialized:", {
      totalBeats: customBeats.length,
      dates: customBeats.map((b) => b.date),
      fileBeatsLoaded: fileBeats.length,
    });

    // Mark as initialized and call callbacks
    isInitialized = true;
    initCallbacks.forEach((callback) => callback());
    initCallbacks.length = 0; // Clear callbacks array
  } catch (error) {
    console.error("Failed to load custom beats:", error);
    // Initialize with weekly beats even if localStorage fails
    weeklyBeats.forEach((weeklyBeat) => {
      if (!customBeats.some((beat) => beat.date === weeklyBeat.date)) {
        customBeats.push(weeklyBeat);
      }
    });

    // Mark as initialized even if loading failed
    isInitialized = true;
    initCallbacks.forEach((callback) => callback());
    initCallbacks.length = 0;
  }
};

// Initialize on client-side only
if (typeof window !== "undefined") {
  // Initialize immediately to avoid race conditions
  initializeCustomBeats().then(() => {
    console.log("Custom beats loaded:", {
      totalBeats: customBeats.length,
      dates: customBeats.map((b) => b.date),
      todayBeat: customBeats.find(
        (b) => b.date === new Date().toISOString().split("T")[0]
      ),
    });
  });
}

// Get custom beat for a specific date
export const getCustomBeat = (date: string): CustomBeat | null => {
  return customBeats.find((beat) => beat.date === date) || null;
};

// Add a custom beat
export const addCustomBeat = (beat: CustomBeat): void => {
  // Remove existing beat for the same date if it exists
  customBeats = customBeats.filter((b) => b.date !== beat.date);

  // Add the new beat
  customBeats.push(beat);

  // Save to localStorage
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(
        "beatkerri_custom_beats",
        JSON.stringify(customBeats)
      );
    } catch (error) {
      console.error("Failed to save custom beats:", error);
    }
  }
};

// Remove a custom beat
export const removeCustomBeat = (date: string): void => {
  customBeats = customBeats.filter((b) => b.date !== date);
  if (typeof window !== "undefined") {
    try {
      localStorage.setItem(
        "beatkerri_custom_beats",
        JSON.stringify(customBeats)
      );
    } catch (error) {
      console.error("Failed to save custom beats:", error);
    }
  }
};

// Get all custom beats
export const getAllCustomBeats = (): CustomBeat[] => {
  return [...customBeats];
};

// Check if a date has a custom beat
export const hasCustomBeat = (date: string): boolean => {
  return customBeats.some((beat) => beat.date === date);
};

// Clear localStorage and reinitialize custom beats (for testing)
export const clearAndReinitializeCustomBeats = (): void => {
  if (typeof window !== "undefined") {
    localStorage.removeItem("beatkerri_custom_beats");
    customBeats = [];
    initializeCustomBeats();
    console.log("Custom beats cleared and reinitialized");
  }
};

/**
 * Get beat for a specific date with automatic fallback
 *
 * Priority order:
 * 1. Check hardcoded weeklyBeats array (for past dates)
 * 2. Check customBeats loaded from JSON files (stored in localStorage)
 * 3. **Fallback**: Use auto-generated beat if no custom beat exists
 *
 * This ensures the game always has a beat to play, even if:
 * - JSON files fail to load
 * - No custom beat is defined for the date
 * - Network or file system errors occur
 */
export const getBeatForDate = (
  date: string,
  generatedBeat: boolean[][],
  generatedBpm: number
): {
  grid: boolean[][];
  bpm: number;
  isCustom: boolean;
  title?: string;
  description?: string;
  creator?: string;
  category?: string;
} => {
  // First check the in-memory weeklyBeats array (works during SSR)
  const weeklyBeat = weeklyBeats.find((beat) => beat.date === date);
  if (weeklyBeat) {
    console.log("🎯 Found weekly beat for", date, ":", weeklyBeat.title);
    return {
      grid: weeklyBeat.grid,
      bpm: weeklyBeat.bpm,
      isCustom: true,
      title: weeklyBeat.title,
      description: weeklyBeat.description,
      creator: weeklyBeat.creator,
      category: weeklyBeat.category,
    };
  }

  // Then check localStorage-based custom beats (loaded from JSON files)
  const customBeat = getCustomBeat(date);
  if (customBeat) {
    console.log("🎯 Found custom beat from JSON for", date);
    return {
      grid: customBeat.grid,
      bpm: customBeat.bpm,
      isCustom: true,
      title: customBeat.title,
      description: customBeat.description,
      creator: customBeat.creator,
      category: customBeat.category,
    };
  }

  // FALLBACK: Use auto-generated beat (always available)
  console.log(
    "🎯 No custom beat found for",
    date,
    "- using auto-generated beat"
  );
  return {
    grid: generatedBeat,
    bpm: generatedBpm,
    isCustom: false,
  };
};
